<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Emby.MyAnimeList.Plugin</AssemblyName>
    <RootNamespace>Emby.MyAnimeList.Plugin</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediaBrowser.Server.Core" Version="4.9.1.90" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\configPage.html" />
  </ItemGroup>

  <Target Name="CopyToEmbyPlugins" AfterTargets="Build" Condition="'$(EmbyPluginPath)' != ''">
    <MakeDir Directories="$(EmbyPluginPath)" />
    <Copy SourceFiles="@(ReferenceCopyLocalPaths);$(TargetPath)" DestinationFolder="$(EmbyPluginPath)" SkipUnchangedFiles="true" />
  </Target>
</Project>
